### ISSUE TITLE
Windows: Program shows plot for little duration.

### ISSUE THREAD

**Issue by HammadRehman** [yuchsiao/eggplot#1]
Hi When I run the program plot displays for very little time and then it disappears. Will you please tell me how can I display plot for long duration?

Regards

**Comment by yuchsiao** [comment]
It sounds to me the same question when people are printing out message from an IDE and it appears when the program ends. People oftentimes add a line of code to ask for another user input (for an "enter" for instance) to keep the program alive. Is that your scenario?
